name: 'Helm Push'
description: 'Push Helm charts to a repository using Helm 3'
author: 'Flownative'
inputs:
  charts_folder:
    description: 'Name of the parent folder containing the individual Helm chart directories.'
    required: false
    default: '.'
  chart_name:
    description: 'Name of the Helm chart, to be used in the URI to push to. For example, `coffee-manager`'
    required: true
    default: ''
  chart_version:
    description: 'The tag / version to use as a chart version. For example, `1.2.5-12`. A "v" prefix will be stripped automatically.'
    required: true
    default: ''
  app_version:
    description: 'The tag / version to use as an app version. For example, `1.2.5-12`. A "v" prefix will be stripped automatically.'
    required: true
    default: ''
  registry_host:
    description: 'Host name of the OCI compatible registry. For instance: "harbor.example.com"'
    required: true
    default: ''
  repository_path:
    description: 'Relative path leading to the repository to push to. For instance: "acme-charts"'
    required: true
    default: ''
  repository_user:
    description: 'Username to use for authenticating against the chart repository'
    required: true
    default: ''
  repository_password:
    description: 'Password to use for authenticating against the chart repository'
    required: true
    default: ''

runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'package'
  color: 'blue'
